# Generated by Django 3.2.9 on 2021-12-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211129_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='area_alias',
            field=models.CharField(choices=[('FISM', '정보보호관리체계'), ('SRV', '서버'), ('DBM', '데이터베이스'), ('INF', '네트워크 인프라'), ('NET', '네트워크 장비'), ('ISS', '정보보호시스템'), ('WEB', '웹 애플리케이션'), ('MOB', '모바일 애플리케이션'), ('HTS', 'HTS')], max_length=10, verbose_name='분야'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='full_code',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='자산전체코드'),
        ),
    ]
