# Generated by Django 3.2.9 on 2021-12-29 00:38

import api.models.upload_file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211212_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_server',
            field=models.BooleanField(choices=[(False, '아니오'), (True, '예')], default=True, verbose_name='서버측 점검 여부'),
        ),
        migrations.AlterField(
            model_name='poc',
            name='auto_result',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='자동판단결과'),
        ),
        migrations.AlterField(
            model_name='poc',
            name='point',
            field=models.TextField(blank=True, default='', verbose_name='취약항목'),
        ),
        migrations.AlterField(
            model_name='poc',
            name='result',
            field=models.CharField(default='Y', max_length=10, verbose_name='취약여부'),
        ),
        migrations.AlterField(
            model_name='poc',
            name='vulnerability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocs', to='api.vulnerability'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='auto_result',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='자동분석결과'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.upload_file.get_screenshot_upload_to, verbose_name='스크린샷')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='api.vulnerability')),
            ],
        ),
    ]
