# Generated by Django 3.2.9 on 2021-12-29 13:31

import api.models.upload_file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211229_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='RerferFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.upload_file.get_referfile_upload_to, verbose_name='첨부파일')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referfiles', to='api.vulnerability')),
            ],
        ),
    ]
