# Generated by Django 3.2.9 on 2022-01-02 23:31

import api.models.upload_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rerferfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poc',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='compliance',
            name='year',
            field=models.SmallIntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049)], default=2022, verbose_name='발표 년도'),
        ),
        migrations.AlterField(
            model_name='rerferfile',
            name='file',
            field=models.FileField(upload_to=api.models.upload_file.get_referfile_upload_to, verbose_name='참고파일'),
        ),
    ]
